--liquibase formatted sql
--changeset spaceship-management:roles  runOnChange:true

CREATE TABLE IF NOT EXISTS roles
(
    id        BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    role_name VARCHAR(50) NOT NULL UNIQUE
);