--liquibase formatted sql
--changeset spaceship-management:spaceships  runOnChange:true

CREATE TABLE IF NOT EXISTS spaceships
(
    id              BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name            VARCHAR(255)          NOT NULL,
    series_or_movie VARCHAR(255),
    type            VARCHAR(100)          NOT NULL,
    crew_capacity   INT,
    is_deleted      BOOLEAN DEFAULT FALSE NOT NULL
);